[package]
name = "user/tutorial"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
packet = "rajden28/packet@1.7.3"
promise = "evaera/promise@4.0.0"
dataservice = "leifstout/dataservice@0.3.2"

[server-dependencies]
